第3回課題
asato-2023/RaiseTech-AWS pull request #2
Opened 2023-06-06 14:11 UTC by asato-2023

第3回課題を提出いたします。ご確認をお願いいたします。
lecture03.mdに今回の学びを記載しております。
画像の埋め込みがうまくいかなかったため、今回はimageディレクトリ内に画像格納のみとしております。
理由は、「感想」のところに記載しています。

2023-06-06 15:30 UTC, MasatoshiMizumoto requested changes
画像の表示方法をコメント入れたので、`Files Changed`からご確認ください！

2023-06-06 15:30 UTC, MasatoshiMizumoto commented on lecture03.md
> +`kadai3-1.png`
画像表示はこうです！
```suggestion
![kadai3-1](./image/kadai3-1.png)
```

2023-06-06 15:33 UTC, asato-2023 commented on lecture03.md
> +`kadai3-1.png`
ご確認ありがとうございます。
記載いただいた通りに入力しても、Cloud9のプレビューで表示されなかったので、今回削除した状況です。

2023-06-06 15:35 UTC, MasatoshiMizumoto commented on lecture03.md
> +`kadai3-1.png`
Cloud9だとプレビューされないんで、Cloud9で表示されるかは無視してOKです！
GitHubで表示されるかで判断ください！

2023-06-06 15:36 UTC, asato-2023 commented on lecture03.md
> +`kadai3-1.png`
そうだったのですね。。承知しました。
lecture03.mdのみ再提出しますので、お待ちください。

2023-06-07 12:39 UTC, asato-2023 commented
lecture03.mdを修正しました。
ご確認をお願いいたします。
[60423a2](https://github.com/asato-2023/RaiseTech-AWS/pull/2/commits/60423a298392f253e36bfae06fdd7335cf5133b1)

2023-06-08 03:50 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-06-08 11:23 UTC, merged