第5回課題提出のため
asato-2023/RaiseTech-AWS pull request #4
Opened 2023-09-18 13:46 UTC by asato-2023

第5回課題を提出いたします。
ご確認よろしくお願いいたします。

2023-09-18 13:55 UTC, MasatoshiMizumoto requested changes
2点変更依頼としてコメントしました！
よろしくおねがいします！

2023-09-18 13:55 UTC, MasatoshiMizumoto commented on image3/.DS_Store
`.DS_Store`は不要ファイルなので削除と、gitで管理されないように除外してください！

2023-09-18 13:55 UTC, MasatoshiMizumoto commented on image3/kouseizu.png
構成図ですがモノクロアイコンが混在してるかもしれないので、ちょっと見直してみてください！

2023-09-18 13:55 UTC, MasatoshiMizumoto commented on lecture05.md
この報告はOKです:+1:

2023-09-24 11:55 UTC, asato-2023 commented on image3/.DS_Store
除外しました。誤って全ファイルキャッシュクリアしてしまったので、上げ直しになっています。

2023-09-24 11:57 UTC, asato-2023 commented on image3/kouseizu.png
構成図修正しました。図を選ぶ際に全ての検索結果ではなく、一部の結果のまま選択していたためモノクロを選んでいたようです。

2023-09-24 11:59 UTC, asato-2023 commented
不要ファイルの削除と、画像のアイコンを編集し直しました。
ご確認をお願いいたします。
（不要ファイル削除の際に、キャッシュクリアを全てのファイルで実行してしまったため、全て上げ直しになっています。）
[3ac084f](https://github.com/asato-2023/RaiseTech-AWS/pull/4/commits/3ac084fbc7d6da1dfd99660a0cdff3df8f56d57e)

2023-09-25 06:44 UTC, MasatoshiMizumoto requested changes
最後1点だけご対応お願いします！！

2023-09-25 06:44 UTC, MasatoshiMizumoto commented on .gitignore
最終行が改行ではないエラーを検知しているので改行をお願いします！！

2023-09-25 06:44 UTC, MasatoshiMizumoto commented on image3/kouseizu.png
構成図OKです！

2023-09-25 15:21 UTC, asato-2023 commented on .gitignore
改行修正しました。

2023-09-25 15:23 UTC, asato-2023 commented
.gitignoreの改行エラー修正しました。
ご確認をお願いします。
[1253641](https://github.com/asato-2023/RaiseTech-AWS/pull/4/commits/1253641f4c7077a25ddbc64f6d7cb5280bbc0ed7)

2023-09-26 01:26 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-10-03 10:24 UTC, merged